name = "mybirthday-myx-is"
main = "modules/mobile-app-shell/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "QUIZ_DATA"
id = "3ab11a174e29413484c758a94ba60faa"

routes = [
  { pattern = "mybirthday.myx.is", custom_domain = true }
]
