name = "mybirthday-myx-is"
main = "modules/mobile-app-shell/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

routes = [
  { pattern = "mybirthday.myx.is", custom_domain = true }
]

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[[kv_namespaces]]
binding = "QUIZ_DATA"
id = "3ab11a174e29413484c758a94ba60faa"

[[d1_databases]]
binding = "DB"
database_name = "its_my_birthday_db"
database_id = "4b088586-b24f-45d6-9728-f255d173800e"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "its-my-birthday-media"

[ai]
binding = "AI"

[vars]
APP_NAME = "MYX.IS"
PORTAL = "mybirthday"

[observability]
enabled = true
